import dynamic from "next/dynamic";
const Chart = dynamic(() => import("react-apexcharts"), { ssr: false });
import { useTheme } from "@mui/material/styles";
import { Box, Typography, useMediaQuery } from "@mui/material";
import InsightsIcon from "@mui/icons-material/Insights";

import DashboardWidgetCard from "../../shared/DashboardWidgetCard";
import SkeletonEmployeeSalaryCard from "../skeleton/EmployeeSalaryCard";
import DashboardCard from "../../shared/DashboardCard";

interface EmployeeSalaryCardProps {
  isLoading?: boolean;
}

const Insights = ({ isLoading }: EmployeeSalaryCardProps) => {
  const theme = useTheme();
  const isLargeScreen = useMediaQuery(theme.breakpoints.up("lg"));

  return (
    <>
      {isLoading ? (
        <SkeletonEmployeeSalaryCard />
      ) : (
        <DashboardCard
          title="Sentiment Insights"
          subtitle="Generated by the Month"
        >
          <>
            <Box
              sx={{
                minHeight: isLargeScreen ? "303px" : "auto",
                display: "flex",

                border: "black",
              }}
            >
              <Typography
                sx={{
                  fontSize: {
                    xs: "1rem",
                    lg: "1.1rem",
                  },
                  lineHeight: 1.5,
                }}
                color="textSecondary"
              >
                Secara keseluruhan, umpan balik tampaknya berpusat pada kualitas
                layanan pelanggan, pengalaman produk, dan peningkatan penjualan,
                dengan sentimen yang berpotensi beragam yang sedikit condong ke
                arah ketidakpuasan di beberapa area.
              </Typography>
            </Box>
          </>
        </DashboardCard>
      )}
    </>
  );
};

export default Insights;
