export interface ProductType {
  id: number;
  nama_agent: string;
  kode_gerai: string;
  store: string;
  area: string;
  menu: string;
  percentage_service: string;
  percentage_toilet: string;
  percentage_food: string;
  createdAt: string;
  image_product: string;
  image_struk: string;
  menu_makanan: string;
  [key: string]: string | number | boolean | string[] | Date;
}

export interface Product {
  id: number;
  nik_agent: string;
  umur_agent: string;
  store_name: string;
  area: string;
  kode_gerai: string;
  product: string;
  jam_service_dimulai: string;
  pelayanan_kurang_10_menit?: string;
  time2: string;
  foto_bill: string | null;
  foto_bill_aplikasi: string | null;
  foto_product: string | null;
  foto_lainnya: string | null;
  jam_product_diterima?: string | null;
  kasir_p1: string;
  crew_p1: string;
  kemas_p1: string;
  kemas_p2: string | null;
  kemas_comment: string | null;
  porsi_p1: string;
  porsi_p2: string | null;
  porsi_comment: string | null;
  rasa_product_p1: string;
  rasa_product_p2: string | null;
  rasa_product_comment: string | null;
  tekstur_p1: string;
  tekstur_p2: string | null;
  tekstur_comment: string | null;
  kesegaran_makanan_p1: string;
  kesegaran_makanan_p2: string | null;
  kesegaran_makanan_comment: string | null;
  kematangan_product_p1: string;
  kematangan_product_p2: string | null;
  kematangan_product_comment: string | null;
  tingkat_kepuasan: string;
  nominal: string;
  nominal_aplikasi: string | null;
  comment: string;
  // Z1002: string | null;
  // Z1003: string | null;
  cm_status: number;
  cm_user: string;
  store: string;
  lingkeb_1: string | null;
  total_crew: string | null;
  menu_makanan: string;
  menu_minuman: string;
  nama_staff: string;
  jam_pemesanan: string;
  jam_pada_bill: string;
  jam_penerimaan_makanan: string;
  [key: string]: any;
}
