import mock from "../mock";
import { sub } from "date-fns";
import { Chance } from "chance";

const chance = new Chance();

const ProductsData = [
  {
    nama_agent: "Agent 1",
    kode_gerai: "Kode Agent",
    id: 1,
    store: "Store",
    area: "Area",
    menu: "Menu",
    percentage_service: "10/10",
    percentage_toilet: "10/10",
    percentage_food: "10/10",
    date: sub(new Date(), { days: 8, hours: 6, minutes: 20 }),
    foto_produk: "/images/products/s7.jpg",
    foto_struk: "/images/products/s7.jpg",
  },
  {
    nama_agent: "Agent",
    kode_gerai: "Kode Agent",
    id: 2,
    store: "Store",
    area: "Area",
    menu: "Menu",
    percentage_service: "10/10",
    percentage_toilet: "10/10",
    percentage_food: "10/10",
    date: "",
    foto_produk: "/images/products/s7.jpg",
    foto_struk: "/images/products/s7.jpg",
  },
  {
    nama_agent: "Agent",
    kode_gerai: "Kode Agent",
    id: 3,
    store: "Store",
    area: "Area",
    menu: "Menu",
    percentage_service: "10/10",
    percentage_toilet: "10/10",
    percentage_food: "10/10",
    date: "",
    foto_produk: "/images/products/s7.jpg",
    foto_struk: "/images/products/s7.jpg",
  },
  {
    nama_agent: "Agent",
    kode_gerai: "Kode Agent",
    id: 4,
    store: "Store",
    area: "Area",
    menu: "Menu",
    percentage_service: "10/10",
    percentage_toilet: "10/10",
    percentage_food: "10/10",
    date: "",
    foto_produk: "/images/products/s7.jpg",
    foto_struk: "/images/products/s7.jpg",
  },
  {
    id: 5,
    nama_agent: "Agent",
    kode_gerai: "Kode Agent",
    store: "Store",
    area: "Area",
    menu: "Menu",
    percentage_service: "10/10",
    percentage_toilet: "10/10",
    percentage_food: "10/10",
    date: "",
    foto_produk: "/images/products/s7.jpg",
    foto_struk: "/images/products/s7.jpg",
  },
  {
    id: 6,
    nama_agent: "Agent",
    kode_gerai: "Kode Agent",
    store: "Store",
    area: "Area",
    menu: "Menu",
    percentage_service: "10/10",
    percentage_toilet: "10/10",
    percentage_food: "10/10",
    date: "",
    foto_produk: "/images/products/s7.jpg",
    foto_struk: "/images/products/s7.jpg",
  },
  {
    id: 7,
    nama_agent: "Agent",
    kode_gerai: "Kode Agent",
    store: "Store",
    area: "Area",
    menu: "Menu",
    percentage_service: "10/10",
    percentage_toilet: "10/10",
    percentage_food: "10/10",
    date: sub(new Date(), { days: 6, hours: 10, minutes: 0 }),
    foto_produk: "/images/products/s7.jpg",
    foto_struk: "/images/products/s7.jpg",
  },
  {
    id: 8,
    nama_agent: "Agent",
    kode_gerai: "Kode Agent",
    store: "Store",
    area: "Area",
    menu: "Menu",
    percentage_service: "10/10",
    percentage_toilet: "10/10",
    percentage_food: "10/10",
    date: "",
    foto_produk: "/images/products/s7.jpg",
    foto_struk: "/images/products/s7.jpg",
  },
  {
    id: 9,
    nama_agent: "Agent",
    kode_gerai: "Kode Agent",
    store: "Store",
    area: "Area",
    menu: "Menu",
    percentage_service: "10/10",
    percentage_toilet: "10/10",
    percentage_food: "10/10",
    date: "",
    foto_produk: "/images/products/s7.jpg",
    foto_struk: "/images/products/s7.jpg",
  },
  {
    id: 10,
    nama_agent: "Agent",
    kode_gerai: "Kode Agent",
    store: "Store",
    area: "Area",
    menu: "Menu",
    percentage_service: "10/10",
    percentage_toilet: "10/10",
    percentage_food: "10/10",
    date: "",
    foto_produk: "/images/products/s7.jpg",
    foto_struk: "/images/products/s7.jpg",
  },
];

mock.onGet("/api/data/eCommerce/ProductsData").reply(() => {
  return [200, ProductsData];
});

export default ProductsData;
