import { Product } from "@/app/(DashboardLayout)/types/apps/visit";

export const getLogoKey = (brandId: number, mode: "light" | "dark") => {
  const logoMap: Record<number, { light: string; dark: string; width: number; height: number }> = {
    1: {
      light: "/images/logos/haus-logo.png",
      dark: "/images/logos/haus-logo.png",
      width: 150,
      height: 50,
    },
    2: {
      light: "/images/logos/jiwa-logo.png",
      dark: "/images/logos/jiwa-logo.png",
      width: 130,
      height: 50,
    },
    3: {
      light: "/images/logos/hangry.png",
      dark: "/images/logos/hangry.png",
      width: 150,
      height: 50,
    },
    4: {
      light: "/images/logos/darmi.png",
      dark: "/images/logos/darmi.png",
      width: 100,
      height: 70,
    },
  };

  return (
    logoMap[brandId] || {
      light: "/images/logos/topan.png",
      dark: "/images/logos/topan.png",
      width: 150,
      height: 50,
    }
  );
};

export const getTitleKey = (brandId: number): string => {
  const brandMap: Record<number, string> = {
    1: "Haus",
    2: "Janji Jiwa",
    3: "Hangry",
    4: "Darmi",
  };

  return brandMap[brandId] || "Tokopandai";
};

export const getInitialValues = (selectedData: Product | null, brandId: number): Partial<Product> => {
  const commonFields: Partial<Product> = {
    id: selectedData?.id ?? 0,
    kode_gerai: selectedData?.kode_gerai ?? "",
    nama_agent: selectedData?.nama_agent ?? "",
    area: selectedData?.area ?? "",
    // data below taruh terakhiran setelah urutan dari commonfields

    cm_user: selectedData?.cm_user ?? "",
    cm_status: selectedData?.cm_status ?? 0,
    createdAt: selectedData?.createdAt ?? "",
  };

  switch (brandId) {
    case 4: // Darmi
      return {
        ...commonFields,
        store_name: selectedData?.store_name ?? "",
        area_manager: selectedData?.area_manager ?? "",
        menu: selectedData?.menu ?? "",
        crewc: selectedData?.crewc ?? "",
        crewp: selectedData?.crewp ?? "",
        crews: selectedData?.crews ?? "",
        total_crew: selectedData?.total_crew ?? "",
        hc: selectedData?.hc ?? "",
        time_exp: selectedData?.time_exp ?? "",
        time_ser: selectedData?.time_ser ?? "",
        antrian: selectedData?.antrian ?? "",
        kepuasan: selectedData?.kepuasan ?? "",
        pkem1: selectedData?.pkem1 ?? "",
        pkem2: selectedData?.pkem2 ?? "",
        pfs1: selectedData?.pfs1 ?? "",
        pfs2: selectedData?.pfs2 ?? "",
        pkp1: selectedData?.pkp1 ?? "",
        scas1: selectedData?.scas1 ?? "",
        scas2: selectedData?.scas2 ?? "",
        scas3: selectedData?.scas3 ?? "",
        scas4: selectedData?.scas4 ?? "",
        scas5: selectedData?.scas5 ?? "",
        scas6: selectedData?.scas6 ?? "",
        scas7: selectedData?.scas7 ?? "",
        scas8: selectedData?.scas8 ?? "",
        scas9: selectedData?.scas9 ?? "",
        scas10: selectedData?.scas10 ?? "",
        scas11: selectedData?.scas11 ?? "",
        scas12: selectedData?.scas12 ?? "",
        scas13: selectedData?.scas13 ?? "",
        scas14: selectedData?.scas14 ?? "",
        scas15: selectedData?.scas15 ?? "",
        scas16: selectedData?.scas16 ?? "",
        scas17: selectedData?.scas17 ?? "",
        scas18: selectedData?.scas18 ?? "",
        scas19: selectedData?.scas19 ?? "",
        spro1: selectedData?.spro1 ?? "",
        spro2: selectedData?.spro2 ?? "",
        spro3: selectedData?.spro3 ?? "",
        spro4: selectedData?.spro4 ?? "",
        sser1: selectedData?.sser1 ?? "",
        sser2: selectedData?.sser2 ?? "",
        sser3: selectedData?.sser3 ?? "",
        sser4: selectedData?.sser4 ?? "",
        sser5: selectedData?.sser5 ?? "",
        sser6: selectedData?.sser6 ?? "",
        speo1: selectedData?.speo1 ?? "",
        speo2: selectedData?.speo2 ?? "",
        speo3: selectedData?.speo3 ?? "",
        speo4: selectedData?.speo4 ?? "",
        speo5: selectedData?.speo5 ?? "",
        speo6: selectedData?.speo6 ?? "",
        speo7: selectedData?.speo7 ?? "",
        speo8: selectedData?.speo8 ?? "",
        tto1: selectedData?.tto1 ?? "",
        tto2: selectedData?.tto2 ?? "",
        tto3: selectedData?.tto3 ?? "",
        tto4: selectedData?.tto4 ?? "",
        tto5: selectedData?.tto5 ?? "",
        tto6: selectedData?.tto6 ?? "",
        tto7: selectedData?.tto7 ?? "",
        tto8: selectedData?.tto8 ?? "",
        tto9: selectedData?.tto9 ?? "",
        tto10: selectedData?.tto10 ?? "",
        clc1: selectedData?.clc1 ?? "",
        clc2: selectedData?.clc2 ?? "",
        clc3: selectedData?.clc3 ?? "",
        clc4: selectedData?.clc4 ?? "",
        clc5: selectedData?.clc5 ?? "",
        clc6: selectedData?.clc6 ?? "",
        clc7: selectedData?.clc7 ?? "",
        clc8: selectedData?.clc8 ?? "",
        clc9: selectedData?.clc9 ?? "",
        clc10: selectedData?.clc10 ?? "",
        clc11: selectedData?.clc11 ?? "",
        clc12: selectedData?.clc12 ?? "",
        clc13: selectedData?.clc13 ?? "",
        clc14: selectedData?.clc14 ?? "",
        clc15: selectedData?.clc15 ?? "",
        clc16: selectedData?.clc16 ?? "",
        clc17: selectedData?.clc17 ?? "",
        clc18: selectedData?.clc18 ?? "",
        clc19: selectedData?.clc19 ?? "",
        clc20: selectedData?.clc20 ?? "",
        nominal_struk: selectedData?.nominal_struk ?? "",
        catatan: selectedData?.catatan ?? "",
        penjelasan_comp: selectedData?.penjelasan_comp ?? "",
        rekomendasi: selectedData?.rekomendasi ?? "",
        img_petugas: selectedData?.img_petugas ?? "",
        img_product: selectedData?.img_product ?? "",
        img_dll: selectedData?.img_dll ?? "",
        nik_agent: selectedData?.nik_agent ?? "",
      };
    case 3: // Hangry
      return {
        ...commonFields,
        store_name: selectedData?.store_name ?? "",
        product: selectedData?.product ?? "",
        cm_status: selectedData?.cm_status ?? 0,
        nik_agent: selectedData?.nik_agent ?? "",
        umur_agent: selectedData?.umur_agent ?? "",
        jam_service_dimulai: selectedData?.jam_service_dimulai ?? "",
        time2: selectedData?.time2 ?? "",
        foto_bill: selectedData?.foto_bill ?? "",
        foto_bill_aplikasi: selectedData?.foto_bill_aplikasi ?? "",
        foto_product: selectedData?.foto_product ?? "",
        foto_lainnya: selectedData?.foto_lainnya ?? "",
        jam_product_diterima: selectedData?.jam_product_diterima ?? "",
        kasir_p1: selectedData?.kasir_p1 ?? "",
        crew_p1: selectedData?.crew_p1 ?? "",
        kemas_p1: selectedData?.kemas_p1 ?? "",
        kemas_p2: selectedData?.kemas_p2 ?? "",
        kemas_image: selectedData?.kemas_image ?? "",
        kemas_comment: selectedData?.kemas_comment ?? "",
        porsi_p1: selectedData?.porsi_p1 ?? "",
        porsi_p2: selectedData?.porsi_p2 ?? "",
        porsi_image: selectedData?.porsi_image ?? "",
        porsi_comment: selectedData?.porsi_comment ?? "",
        rasa_product_p1: selectedData?.rasa_product_p1 ?? "",
        rasa_product_p2: selectedData?.rasa_product_p2 ?? "",
        rasa_product_comment: selectedData?.rasa_product_comment ?? "",
        tekstur_p1: selectedData?.tekstur_p1 ?? "",
        tekstur_p2: selectedData?.tekstur_p2 ?? "",
        tekstur_image: selectedData?.tekstur_image ?? "",
        tekstur_comment: selectedData?.tekstur_comment ?? "",
        kesegaran_makanan_p1: selectedData?.kesegaran_makanan_p1 ?? "",
        kesegaran_makanan_p2: selectedData?.kesegaran_makanan_p2 ?? "",
        kesegaran_makanan_comment: selectedData?.kesegaran_makanan_comment ?? "",
        kematangan_product_p1: selectedData?.kematangan_product_p1 ?? "",
        kematangan_product_p2: selectedData?.kematangan_product_p2 ?? "",
        kematangan_product_comment: selectedData?.kematangan_product_comment ?? "",
        tingkat_kepuasan: selectedData?.tingkat_kepuasan ?? "",
        nominal: selectedData?.nominal ?? "",
        nominal_aplikasi: selectedData?.nominal_aplikasi ?? "",
        comment: selectedData?.comment ?? "",
        jam_pemesanan: selectedData?.jam_pemesanan ?? "",
        jam_pada_bill: selectedData?.jam_pada_bill ?? "",
        jam_penerimaan_makanan: selectedData?.jam_penerimaan_makanan ?? "",
        cm_user: selectedData?.cm_user ?? "",
        kurang_dari_10menit: selectedData?.kurang_dari_10menit ?? "",
      };
    case 2: // Janji Jiwa
      return {
        ...commonFields,
        store_name: selectedData?.store_name ?? "",
        total_crew: selectedData?.total_crew ?? "",
        nama_staff: selectedData?.nama_staff ?? "",
        menu_makanan: selectedData?.menu_makanan ?? "",
        menu_minuman: selectedData?.menu_minuman ?? "",
        antrian: selectedData?.antrian ?? "",
        time_1: selectedData?.time_1 ?? "",
        time_2: selectedData?.time_2 ?? "",
        waktu_masuk: selectedData?.waktu_masuk ?? "",
        waktu_dilayani: selectedData?.waktu_dilayani ?? "",
        waktu_terima_produk: selectedData?.waktu_terima_produk ?? "",
        lingkeb_1: selectedData?.lingkeb_1 ?? "",
        lingkeb_1_img: selectedData?.lingkeb_1_img ?? "",
        lingkeb_1_note: selectedData?.lingkeb_1_note ?? "",
        lingkeb_2: selectedData?.lingkeb_2 ?? "",
        lingkeb_2_img: selectedData?.lingkeb_2_img ?? "",
        lingkeb_2_note: selectedData?.lingkeb_2_note ?? "",
        lingkeb_3: selectedData?.lingkeb_3 ?? "",
        lingkeb_3_img: selectedData?.lingkeb_3_img ?? "",
        lingkeb_3_note: selectedData?.lingkeb_3_note ?? "",
        lingkeb_4: selectedData?.lingkeb_4 ?? "",
        lingkeb_4_img: selectedData?.lingkeb_4_img ?? "",
        lingkeb_4_note: selectedData?.lingkeb_4_note ?? "",
        lingkeb_5: selectedData?.lingkeb_5 ?? "",
        lingkeb_5_img: selectedData?.lingkeb_5_img ?? "",
        lingkeb_5_note: selectedData?.lingkeb_5_note ?? "",
        lingkeb_6: selectedData?.lingkeb_6 ?? "",
        lingkeb_6_img: selectedData?.lingkeb_6_img ?? "",
        lingkeb_6_note: selectedData?.lingkeb_6_note ?? "",
        lingkeb_7: selectedData?.lingkeb_7 ?? "",
        lingkeb_7_img: selectedData?.lingkeb_7_img ?? "",
        lingkeb_7_note: selectedData?.lingkeb_7_note ?? "",
        lingkeb_8: selectedData?.lingkeb_8 ?? "",
        lingkeb_8_img: selectedData?.lingkeb_8_img ?? "",
        lingkeb_8_note: selectedData?.lingkeb_8_note ?? "",
        lingkeb_9: selectedData?.lingkeb_9 ?? "",
        lingkeb_9_img: selectedData?.lingkeb_9_img ?? "",
        lingkeb_9_note: selectedData?.lingkeb_9_note ?? "",
        lingkeb_10: selectedData?.lingkeb_10 ?? "",
        lingkeb_10_img: selectedData?.lingkeb_10_img ?? "",
        lingkeb_10_note: selectedData?.lingkeb_10_note ?? "",
        lingkeb_11: selectedData?.lingkeb_11 ?? "",
        lingkeb_11_img: selectedData?.lingkeb_11_img ?? "",
        lingkeb_11_note: selectedData?.lingkeb_11_note ?? "",
        pel_1: selectedData?.pel_1 ?? "",
        pel_1_img: selectedData?.pel_1_img ?? "",
        pel_1_note: selectedData?.pel_1_note ?? "",
        pel_2: selectedData?.pel_2 ?? "",
        // pel_2_img: selectedData?.pel_2_img ?? "",
        pel_2_note: selectedData?.pel_2_note ?? "",
        pel_3: selectedData?.pel_3 ?? "",
        // pel_3_img: selectedData?.pel_3_img ?? "",
        pel_3_note: selectedData?.pel_3_note ?? "",
        pel_4: selectedData?.pel_4 ?? "",
        // pel_4_img: selectedData?.pel_4_img ?? "",
        pel_4_note: selectedData?.pel_4_note ?? "",
        pel_5: selectedData?.pel_5 ?? "",
        // pel_5_img: selectedData?.pel_5_img ?? "",
        pel_5_note: selectedData?.pel_5_note ?? "",
        pel_6: selectedData?.pel_6 ?? "",
        // pel_6_img: selectedData?.pel_6_img ?? "",
        pel_6_note: selectedData?.pel_6_note ?? "",
        pel_7: selectedData?.pel_7 ?? "",
        // pel_7_img: selectedData?.pel_7_img ?? "",
        pel_7_note: selectedData?.pel_7_note ?? "",
        pel_8: selectedData?.pel_8 ?? "",
        // pel_8_img: selectedData?.pel_8_img ?? "",
        pel_8_note: selectedData?.pel_8_note ?? "",
        pel_9: selectedData?.pel_9 ?? "",
        // pel_9_img: selectedData?.pel_9_img ?? "",
        pel_9_note: selectedData?.pel_9_note ?? "",
        pel_10: selectedData?.pel_10 ?? "",
        // pel_10_img: selectedData?.pel_10_img ?? "",
        pel_10_note: selectedData?.pel_10_note ?? "",
        kec_1: selectedData?.kec_1 ?? "",
        // kec_1_img: selectedData?.kec_1_img ?? "",
        // kec_1_note: selectedData?.kec_1_note ?? "",
        kec_2: selectedData?.kec_2 ?? "",
        // kec_2_img: selectedData?.kec_2_img ?? "",
        // kec_2_note: selectedData?.kec_2_note ?? "",
        kec_3: selectedData?.kec_3 ?? "",
        // kec_3_img: selectedData?.kec_3_img ?? "",
        // kec_3_note: selectedData?.kec_3_note ?? "",
        kec_4: selectedData?.kec_4 ?? "",
        // kec_4_img: selectedData?.kec_4_img ?? "",
        // kec_4_note: selectedData?.kec_4_note ?? "",
        kual_1: selectedData?.kual_1 ?? "",
        // kual_1_img: selectedData?.kual_1_img ?? "",
        kual_1_note: selectedData?.kual_1_note ?? "",
        kual_2: selectedData?.kual_2 ?? "",
        // kual_2_img: selectedData?.kual_2_img ?? "",
        kual_2_note: selectedData?.kual_2_note ?? "",
        kual_3: selectedData?.kual_3 ?? "",
        // kual_3_img: selectedData?.kual_3_img ?? "",
        kual_3_note: selectedData?.kual_3_note ?? "",
        kual_4: selectedData?.kual_4 ?? "",
        // kual_4_img: selectedData?.kual_4_img ?? "",
        kual_4_note: selectedData?.kual_4_note ?? "",
        kual_5: selectedData?.kual_5 ?? "",
        // kual_5_img: selectedData?.kual_5_img ?? "",
        kual_5_note: selectedData?.kual_5_note ?? "",
        kual_6: selectedData?.kual_6 ?? "",
        // kual_6_img: selectedData?.kual_6_img ?? "",
        kual_6_note: selectedData?.kual_6_note ?? "",
        kual_7: selectedData?.kual_7 ?? "",
        // kual_7_img: selectedData?.kual_7_img ?? "",
        kual_7_note: selectedData?.kual_7_note ?? "",
        kual_8: selectedData?.kual_8 ?? "",
        // kual_8_img: selectedData?.kual_8_img ?? "",
        kual_8_note: selectedData?.kual_8_note ?? "",
        peng_1: selectedData?.peng_1 ?? "",
        // peng_1_img: selectedData?.peng_1_img ?? "",
        peng_1_note: selectedData?.peng_1_note ?? "",
        peng_2: selectedData?.peng_2 ?? "",
        // peng_2_img: selectedData?.peng_2_img ?? "",
        peng_2_note: selectedData?.peng_2_note ?? "",
        peng_3: selectedData?.peng_3 ?? "",
        // peng_3_img: selectedData?.peng_3_img ?? "",
        peng_3_note: selectedData?.peng_3_note ?? "",
        peng_4: selectedData?.peng_4 ?? "",
        peng_4_img: selectedData?.peng_4_img ?? "",
        peng_4_note: selectedData?.peng_4_note ?? "",
        image_struk: selectedData?.image_struk ?? "",
        image_product: selectedData?.image_product ?? "",
        image_td: selectedData?.image_td ?? "",
        image_lainnya: selectedData?.image_lainnya ?? "",
        summary_1: selectedData?.summary_1 ?? "",
        summary_2: selectedData?.summary_2 ?? "",
        summary_3: selectedData?.summary_3 ?? "",
        alamat_toko: selectedData?.alamat_toko ?? "",
        nik_agent: selectedData?.nik_agent ?? "",
        nama_agent: selectedData?.nama_agent ?? "",
        store_type: selectedData?.store_type ?? "",
        nominal_struk: selectedData?.nominal_struk ?? "",
      };
    case 1: // Haus
      return {
        ...commonFields,
        store_name: selectedData?.store_name ?? "",
        store_type: selectedData?.store_type ?? "",
        menu: selectedData?.menu ?? "",
        A1001: selectedData?.A1001 ?? "",
        A1002: selectedData?.A1002 ?? "",
        A1003: selectedData?.A1003 ?? "",
        A1004: selectedData?.A1004 ?? "",
        A1005: selectedData?.A1005 ?? "",
        A1006: selectedData?.A1006 ?? "",
        A1007: selectedData?.A1007 ?? "",
        A1008: selectedData?.A1008 ?? "",
        A1009: selectedData?.A1009 ?? "",
        A1010: selectedData?.A1010 ?? "",
        A1011: selectedData?.A1011 ?? "",
        A1012: selectedData?.A1012 ?? "",
        A1013: selectedData?.A1013 ?? "",
        A1014: selectedData?.A1014 ?? "",
        A1015: selectedData?.A1015 ?? "",
        A1016: selectedData?.A1016 ?? "",
        A1017: selectedData?.A1017 ?? "",
        A1018: selectedData?.A1018 ?? "",
        A1019: selectedData?.A1019 ?? "",
        A1020: selectedData?.A1020 ?? "",
        A1021: selectedData?.A1021 ?? "",
        A1022: selectedData?.A1022 ?? "",
        A1023: selectedData?.A1023 ?? "",
        A1024: selectedData?.A1024 ?? "",
        A1025: selectedData?.A1025 ?? "",
        A1026: selectedData?.A1026 ?? "",
        A1027: selectedData?.A1027 ?? "",
        A1028: selectedData?.A1028 ?? "",
        A1029: selectedData?.A1029 ?? "",
        A1030: selectedData?.A1030 ?? "",
        A1031: selectedData?.A1031 ?? "",
        A1032: selectedData?.A1032 ?? "",
        A1033: selectedData?.A1033 ?? "",
        A1034: selectedData?.A1034 ?? "",
        A1035: selectedData?.A1035 ?? "",
        A1036: selectedData?.A1036 ?? "",
        A1037: selectedData?.A1037 ?? "",
        A1038: selectedData?.A1038 ?? "",
        A1039: selectedData?.A1039 ?? "",
        B1001: selectedData?.B1001 ?? "",
        B1002: selectedData?.B1002 ?? "",
        B1003: selectedData?.B1003 ?? "",
        B1004: selectedData?.B1004 ?? "",
        B1005: selectedData?.B1005 ?? "",
        B1006: selectedData?.B1006 ?? "",
        B1007: selectedData?.B1007 ?? "",
        B1008: selectedData?.B1008 ?? "",
        Z1001: selectedData?.Z1001 ?? "",
        Z1002: selectedData?.Z1002 ?? "",
        Z1003: selectedData?.Z1003 ?? "",
        Z1004: selectedData?.Z1004 ?? "",
        summary: selectedData?.summary ?? "",
        image_product: selectedData?.image_product ?? "",
        image_struk: selectedData?.image_struk ?? "",
        image_lainnya: selectedData?.image_lainnya ?? "",
        nominal_struk: selectedData?.nominal_struk ?? "",
      };
    default:
      return commonFields;
  }
};
